spring:
  application:
    name: CarRental

  datasource:
    url: jdbc:postgresql://pg-148b2256-car-rental.b.aivencloud.com:16926/defaultdb?sslmode=require
    username: avnadmin
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: carrental

  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://keycloak-local.pl:8443/realms/car-rental
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8081


payu:
  clientId: 486902
  clientSecret: c1bbbfdc86759ff5bb6429d5186cf173
  authUrl: https://secure.snd.payu.com/pl/standard/user/oauth/authorize
  paymentUrl: https://secure.snd.payu.com/api/v2_1/orders

logging:
  level:
    org.springframework.security: DEBUG