version: '3'
services:
  spring-backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-148b2256-car-rental.b.aivencloud.com:16926/defaultdb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_SCHEMA=carrental
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://pg-148b2256-car-rental.b.aivencloud.com:16926/defaultdb?sslmode=require
      KC_DB_USERNAME: avnadmin
      KC_DB_PASSWORD: ${DATABASE_PASSWORD}
      KC_HOSTNAME: https://keycloak-local.pl:8443/
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_SSL_REQUIRED: all
      KC_SSL_KEYSTORE: /etc/x509/https/keycloak.p12
      KC_SSL_KEYSTORE_PASSWORD: ${KEYCLOAK_SSL_PASSWORD}
      KC_SSL_KEYSTORE_TYPE: PKCS12
    ports:
      - "8443:8443"
    command: start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak-theme/carRentalTheme:/opt/keycloak/themes/carRentalTheme
      - ./certs/keycloak.p12:/etc/x509/https/keycloak.p12